import { BASE_RULES, SCRIPT_RULE_OVERRIDES } from './eslint.shared-rules.js';
import js from '@eslint/js';
import globals from 'globals';

export default [
  // ---------------------------------------------------------------------------
  // Generated output. An `ignores`-only entry is a global ignore in flat config.
  //
  // Why this has to exist: every lint gate now runs `eslint .` over the whole
  // package — the pre-push hook (scripts/git-hooks/pre-push, which explains why
  // `.` and not a directory list), .github/workflows/ci.yml, and
  // package.json#scripts.lint alike. Back when package.json still passed
  // `bin/ lib/ scripts/ tests/`, CI ran only that list and these gitignored
  // paths did not exist on a runner at all. The result was a gate that was green
  // on CI and red on every developer machine that had run the autopilot or a
  // coverage report: measured 2026-08-15, `npx eslint .` reported 13 no-undef
  // errors in .ap-boot.mjs and would have blocked every push once the hook was
  // installed. Now that all three share one command, ignoring here is the only
  // place a path can leave the gate — which is why each entry is listed by hand.
  //
  // Scope is deliberately narrow. Both entries are gitignored AND were measured
  // to actually contain lintable files (.ap-boot.mjs: 1, coverage/: 3). The other
  // gitignored paths (_reports/, _benchmarks/, runtime/) are NOT listed: they hold
  // JSON, contained zero lintable files when measured, and if one ever gains a
  // JS file, seeing it is better than silently hiding it.
  //
  // Do not replace this with a parser that reads .gitignore. That would make the
  // lint target set a function of a file maintained for git's purposes, so a
  // future .gitignore entry could shrink lint coverage with nothing on the lint
  // side to review. Every line here removes something from the gate, so each one
  // is listed by hand.
  //
  // Ignoring is also the honest fix rather than adding node globals to these:
  // they are build output, not source, and linting build output has no value.
  {
    ignores: [
      // Autopilot runtime boot artifact, regenerated by the autopilot runtime
      // (.gitignore:15-16). It reappears on any machine that runs autopilot, so
      // this is a recurring artifact and not a one-off local mess.
      '.ap-boot.mjs',
      // Istanbul HTML report assets (block-navigation.js, prettify.js,
      // sorter.js). Vendored third-party files regenerated by `npm run
      // test:coverage`. They happen to pass today only because istanbul ships
      // them with eslint-disable headers, which is not a property to depend on.
      'coverage/',
    ],
  },
  js.configs.recommended,
  {
    files: ['bin/**/*.{js,mjs}', 'lib/**/*.{js,mjs}', 'scripts/**/*.{js,mjs}', 'server/**/*.js', 'tests/**/*.{js,mjs}', 'hooks/**/*.{js,mjs}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
    // Shared with the cowork firewall gate — see eslint.shared-rules.js for why
    // these live in a separate module rather than inline here.
    rules: BASE_RULES,
  },
  {
    files: ['scripts/**/*.{js,mjs}'],
    rules: SCRIPT_RULE_OVERRIDES,
  },
  // ---------------------------------------------------------------------------
  // 5-Layer architecture enforcement (see CLAUDE.md "5-Layer Architecture").
  // Upper layers import lower only: 5 Runtime -> 4 Cognitive -> 3 Learning
  // -> 2 Auxiliary -> 1 Core. A lower layer importing an upper layer is a
  // violation. Enforced via the built-in no-restricted-imports rule (zero new
  // deps). Patterns match the import specifier string with minimatch globs, so
  // `**/<layer>/**` catches relative imports at any nesting depth
  // (`../cognitive/x`, `../../cognitive/x`). JSDoc type-only `import('...')`
  // is not an import statement, so it is naturally exempt.
  // ---------------------------------------------------------------------------
  {
    // L1 Core: must not import from ANY higher layer (L2/L3/L4/L5).
    // utils/ = pure leaf helpers (core tier); imported downward by all layers.
    files: ['lib/core/**/*.{js,mjs}', 'lib/utils/**/*.{js,mjs}'],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: [
          {
            group: [
              '**/adapters/**', '**/autopilot/**', '**/context/**',
              '**/dispatcher/**', '**/genesis/**', '**/git/**',
              '**/handoff/**', '**/intent/**',
              '**/mcp/**', '**/observability/**', '**/orchestration/**',
              '**/planning/**', '**/privacy/**', '**/release/**', '**/sdk/**',
              '**/security/**', '**/swarm/**', '**/system/**', '**/tui/**',
              '**/visual/**',
              '**/learning/**', '**/cognitive/**', '**/runtime/**',
            ],
            message:
              'Layer violation: lib/core (L1) must not import from a higher layer. Upper layers import lower only (5->4->3->2->1).',
          },
        ],
      }],
    },
  },
  {
    // L2 Auxiliary: must not import from L3 Learning, L4 Cognitive, L5 Runtime.
    //
    // genesis/ (added 2026-08-22): `/go` blueprint renderers. It was in NO
    // layer block, so the allowlist-shaped gate applied zero layer rules to it
    // — fail-open by omission, not by decision. Placed at L2 on two measured
    // grounds: its own imports are node built-ins + `./_shared.js` only (zero
    // lib/* edges), and its only consumers are `commands/go.md` (runtime
    // dynamic import) and tests — no lib module imports it. That is the same
    // "domain service a command drives" profile as release/ visual/ tui/, not
    // the shared-leaf profile of core/ utils/ (L1). Registering is therefore
    // non-breaking today and forward-protective tomorrow.
    // tests/firewall/layer-registration-coverage.test.js keeps this list from
    // silently missing the next new directory.
    files: [
      'lib/adapters/**/*.{js,mjs}', 'lib/autopilot/**/*.{js,mjs}',
      'lib/dispatcher/**/*.{js,mjs}',
      'lib/genesis/**/*.{js,mjs}', 'lib/git/**/*.{js,mjs}',
      'lib/intent/**/*.{js,mjs}', 'lib/mcp/**/*.{js,mjs}',
      'lib/observability/**/*.{js,mjs}', 'lib/orchestration/**/*.{js,mjs}',
      'lib/planning/**/*.{js,mjs}', 'lib/privacy/**/*.{js,mjs}',
      'lib/release/**/*.{js,mjs}', 'lib/sdk/**/*.{js,mjs}',
      'lib/security/**/*.{js,mjs}', 'lib/swarm/**/*.{js,mjs}',
      // supervisor/ (added 2026-09-02): `/split` observe-only control plane
      // (event reducer · run store · lane monitor). Imports lib/git and
      // lib/observability only — same L2 profile as git/ and observability/.
      'lib/supervisor/**/*.{js,mjs}',
      'lib/system/**/*.{js,mjs}', 'lib/tui/**/*.{js,mjs}',
      'lib/visual/**/*.{js,mjs}',
    ],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: [
          {
            group: ['**/learning/**', '**/cognitive/**', '**/runtime/**'],
            message:
              'Layer violation: lib auxiliary (L2) must not import from the learning (L3), cognitive (L4), or runtime (L5) layers. Upper layers import lower only (5->4->3->2->1).',
          },
        ],
      }],
    },
  },
  {
    // L3 Learning: must not import from L4 Cognitive, L5 Runtime.
    // handoff/ is a session-handoff aggregation domain at the learning tier
    // (L3): its highest dependency is learning, and only commands consume it.
    // So L3->L3 (handoff->learning) is a sibling import, not a layer violation.
    files: ['lib/learning/**/*.{js,mjs}', 'lib/handoff/**/*.{js,mjs}'],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: [
          {
            group: ['**/cognitive/**', '**/runtime/**'],
            message:
              'Layer violation: lib/learning (L3) must not import from the cognitive (L4) or runtime (L5) layers. Upper layers import lower only (5->4->3->2->1).',
          },
        ],
      }],
    },
  },
  {
    // L4 Cognitive: must not import from L5 Runtime.
    files: ['lib/cognitive/**/*.{js,mjs}'],
    rules: {
      'no-restricted-imports': ['error', {
        patterns: [
          {
            group: ['**/runtime/**'],
            message:
              'Layer violation: lib/cognitive (L4) must not import from the runtime (L5) layer. Upper layers import lower only (5->4->3->2->1).',
          },
        ],
      }],
    },
  },
  {
    files: ['tests/**/*.{js,mjs}'],
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'max-depth': 'off',
      'complexity': 'off',
    },
  },
  {
    files: ['tests/**/smoke/**/*.{js,mjs}', 'tests/**/*.smoke.{js,mjs}'],
    rules: {
      'no-console': 'off',
    },
  },
];
