#!/usr/bin/env node
/**
 * Swarm Init Script — bootstrap git-based federated swarm.
 *
 * Sets up the user's private swarm repo clone, writes opt-in consent,
 * and enables the git backend in artibot.config.json for future sessions.
 *
 * Usage:
 *   node scripts/swarm-init.js [--repo=<git-url>]
 *   node scripts/swarm-init.js --reset        # remove local clone + consent
 *
 * The repo URL defaults to Yoodaddy0311/artibot-swarm (the user's private
 * federated swarm repo created by `gh repo create`).
 */

import path from 'node:path';
import os from 'node:os';
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { ensureMachineHash, ensureSwarmClone, gitHealthCheck } from '../lib/swarm/git-backend.js';
import { optIn, optOut } from '../lib/swarm/swarm-config.js';
import { ARTIBOT_DIR } from '../lib/core/config.js';
import { getPluginRoot } from '../lib/core/platform.js';
import { atomicWriteSync } from './utils/index.js';

/**
 * Write the portable swarm profile to .claude-plugin/swarm-profile.json.
 * This file travels with the user's artibot fork and lets new devices
 * auto-discover the swarm repo on first install.
 *
 * @param {string} pluginRoot
 * @param {string} repoUrl
 */
function writeSwarmProfile(pluginRoot, repoUrl) {
  const profilePath = path.join(pluginRoot, '.claude-plugin', 'swarm-profile.json');
  const profile = {
    schemaVersion: 1,
    repoUrl,
    backend: 'git',
    createdAt: new Date().toISOString(),
    createdOn: os.hostname(),
    notes: 'Portable swarm profile — safe to commit. Other machines auto-detect and offer opt-in.',
  };
  atomicWriteSync(profilePath, profile);
  return profilePath;
}

const DEFAULT_REPO = 'https://github.com/Yoodaddy0311/artibot-swarm.git';

function out(line) {
  process.stdout.write(line + '\n');
}

function parseArgs() {
  const args = process.argv.slice(2);
  const opts = { repoUrl: DEFAULT_REPO, reset: false };
  for (const arg of args) {
    if (arg === '--reset') opts.reset = true;
    else if (arg.startsWith('--repo=')) opts.repoUrl = arg.slice('--repo='.length);
  }
  return opts;
}

async function resetSwarm() {
  const cloneDir = path.join(ARTIBOT_DIR, 'swarm-git');
  if (existsSync(cloneDir)) {
    rmSync(cloneDir, { recursive: true, force: true });
    out(`Removed clone: ${cloneDir}`);
  }
  await optOut();
  out('Opted out of swarm.');
}

function writeRootScaffoldIfEmpty(cloneDir) {
  const readmePath = path.join(cloneDir, 'README.md');
  if (existsSync(readmePath)) return false;
  const content = `# Artibot Federated Swarm

Private pattern sync repository for Artibot learning data.

This repo is **private** and owned by the user. It stores pattern weights
from the user's own devices for cross-device federated learning.

## Structure

\`\`\`
patterns/
  {machineHash}/
    weights-latest.json    # current state
    history/               # per-sync snapshots
metadata/
  machines.json             # registered devices
\`\`\`

## Privacy

- PII is scrubbed before upload.
- Differential privacy noise is applied to numeric weights.
- Only the user's own devices participate.
- Data never leaves the user's GitHub account.

_Generated by \`scripts/swarm-init.js\`._
`;
  writeFileSync(readmePath, content, 'utf-8');
  const gitignore = path.join(cloneDir, '.gitignore');
  if (!existsSync(gitignore)) {
    writeFileSync(gitignore, '*.log\n.DS_Store\n', 'utf-8');
  }
  return true;
}

async function initSwarm(repoUrl) {
  out(`Initializing swarm with repo: ${repoUrl}`);

  // 1. Clone (or reuse) the swarm repo
  const { cloneDir, freshClone } = await ensureSwarmClone(repoUrl);
  out(`Clone ready at: ${cloneDir} (${freshClone ? 'fresh' : 'existing'})`);

  // 2. Scaffold README on first clone so the repo has at least one commit
  const scaffolded = writeRootScaffoldIfEmpty(cloneDir);
  if (scaffolded) {
    try {
      execSync('git add -A', { cwd: cloneDir, stdio: 'ignore' });
      execSync('git commit -m "swarm: initial scaffold (README + .gitignore)"', {
        cwd: cloneDir,
        stdio: 'ignore',
      });
      // Try push to main, then master
      try {
        execSync('git push -u origin main', { cwd: cloneDir, stdio: 'ignore' });
      } catch {
        execSync('git branch -M main', { cwd: cloneDir, stdio: 'ignore' });
        execSync('git push -u origin main', { cwd: cloneDir, stdio: 'ignore' });
      }
      out('Scaffold pushed to remote.');
    } catch (err) {
      out(`Scaffold push warning: ${err.message}`);
    }
  }

  // 3. Compute + persist machine hash
  const machineHash = await ensureMachineHash();
  out(`Machine hash: ${machineHash}`);

  // 4. Update artibot.config.json to enable git backend
  const pluginRoot = getPluginRoot();
  const configPath = path.join(pluginRoot, 'artibot.config.json');
  const config = JSON.parse(readFileSync(configPath, 'utf-8'));
  config.swarm = {
    ...(config.swarm || {}),
    enabled: true,
    backend: 'git',
    gitRepoUrl: repoUrl,
    syncInterval: 'session',
    localGlobalRatio: [0.3, 0.7],
    differentialPrivacy: {
      enabled: true,
      epsilon: 1.0,
      delta: 1e-5,
    },
  };
  atomicWriteSync(configPath, config);
  out(`Config updated: ${configPath}`);

  // 5. Record opt-in consent
  await optIn();
  out('Consent recorded — opted in.');

  // 6. Write portable profile for auto-detection on other devices
  const profilePath = writeSwarmProfile(pluginRoot, repoUrl);
  out(`Profile written: ${profilePath}`);
  out('  → commit this file to your fork so other devices auto-discover it.');

  // 7. Health check
  const health = await gitHealthCheck({ repoUrl });
  out(`Health: ${health.ok ? 'OK' : 'WARN'} — ${health.message}`);

  out('');
  out('Swarm ready. Patterns will sync on next SessionEnd.');
  out(`Force sync now: node plugins/artibot/scripts/swarm-sync-now.js`);
}

async function main() {
  const opts = parseArgs();
  if (opts.reset) {
    await resetSwarm();
    return;
  }
  await initSwarm(opts.repoUrl);
}

main().catch((err) => {
  process.stderr.write(`[swarm-init] ${err.message || err}\n`);
  process.exit(1);
});
