import { beforeEach, describe, expect, it, vi } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// ---------------------------------------------------------------------------
// Test-only shim for neural-policy.js
//
// NL1 is producing `lib/learning/grpo/neural-policy.js` in parallel. To keep
// this test hermetic regardless of landing order, we create a minimal shim
// on disk at test-file load time if (and only if) the real file does not
// already exist. The shim exports the same surface the factory adapts.
// ---------------------------------------------------------------------------
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const NEURAL_POLICY_PATH = path.resolve(
  __dirname,
  '../../../lib/learning/grpo/neural-policy.js',
);
let createdShim = false;
if (!fs.existsSync(NEURAL_POLICY_PATH)) {
  fs.writeFileSync(
    NEURAL_POLICY_PATH,
    [
      '// Test-only shim autogenerated by policy-factory.test.js.',
      '// Replaced by the real NL1 implementation when that file lands.',
      'export function predict() { return 0.7; }',
      'export function trainBatch() { return { model: {}, episodesUsed: 0 }; }',
      'export function evaluatePolicy() {',
      '  return { logLoss: 0, accuracyVsHeuristic: 1, klFromPrev: 0, samples: 0 };',
      '}',
      'export async function savePolicy() {',
      "  return { policy: { modelType: 'mlp' }, snapshotId: 'mlp-1', policyFile: '' };",
      '}',
      'export async function snapshot() { return ""; }',
      'export async function loadPolicy() { return null; }',
      'export function createPolicyUpdater() { return {}; }',
      '',
    ].join('\n'),
  );
  createdShim = true;
}

// Mock the linear policy-updater surface used by the factory so tests stay
// hermetic (no disk IO, deterministic identity).
vi.mock('../../../lib/learning/grpo/policy-updater.js', () => {
  const store = new Map();
  return {
    predict: vi.fn(() => 0.5),
    trainBatch: vi.fn(() => ({ theta: [1, 2, 3], groupsUsed: 0, episodesUsed: 0, explorationSkipped: 0 })),
    evaluatePolicy: vi.fn(() => ({ logLoss: 0, accuracyVsHeuristic: 1, klFromPrev: 0, samples: 0 })),
    savePolicy: vi.fn(async () => ({ policy: { modelType: 'logistic-regression' }, snapshotId: 'lin-1', policyFile: '/tmp/p.json' })),
    snapshot: vi.fn(async () => '/tmp/snap.json'),
    loadPolicy: vi.fn(async () => null),
    createPolicyUpdater: vi.fn(() => ({ tag: 'linear-updater' })),
    __store: store,
  };
});

const linear = await import('../../../lib/learning/grpo/policy-updater.js');
const {
  createPolicy,
  createPolicyFromFile,
  resolvePolicyType,
  SUPPORTED_TYPES,
  DEFAULT_TYPE,
} = await import('../../../lib/learning/grpo/policy-factory.js');

function makeLogger() {
  return { info: vi.fn(), warn: vi.fn(), error: vi.fn() };
}

beforeEach(() => {
  linear.predict.mockClear();
  linear.trainBatch.mockClear();
  linear.loadPolicy.mockClear();
  linear.savePolicy.mockClear();
  linear.createPolicyUpdater.mockClear();
});

describe('resolvePolicyType', () => {
  it('returns linear as default for empty / non-string inputs', () => {
    const log = makeLogger();
    expect(resolvePolicyType(undefined, log)).toBe('linear');
    expect(resolvePolicyType('', log)).toBe('linear');
    expect(resolvePolicyType(42, log)).toBe('linear');
    expect(log.warn).not.toHaveBeenCalled();
  });

  it('accepts supported types case-insensitively', () => {
    const log = makeLogger();
    expect(resolvePolicyType('linear', log)).toBe('linear');
    expect(resolvePolicyType('MLP', log)).toBe('mlp');
    expect(resolvePolicyType('  Linear  ', log)).toBe('linear');
    expect(log.warn).not.toHaveBeenCalled();
  });

  it('falls back to linear + warns on unknown type', () => {
    const log = makeLogger();
    expect(resolvePolicyType('transformer', log)).toBe('linear');
    expect(log.warn).toHaveBeenCalledTimes(1);
    expect(log.warn.mock.calls[0][0]).toMatch(/unknown modelType/i);
  });

  it('exports stable contract', () => {
    expect(SUPPORTED_TYPES).toEqual(['linear', 'mlp']);
    expect(DEFAULT_TYPE).toBe('linear');
  });
});

describe('createPolicy — default linear', () => {
  it('builds a linear adapter when no type is provided', async () => {
    const adapter = await createPolicy();
    expect(adapter.type).toBe('linear');
    expect(adapter.modelType).toBe('logistic-regression');
    expect(typeof adapter.predict).toBe('function');
    expect(typeof adapter.trainBatch).toBe('function');
    expect(typeof adapter.evaluatePolicy).toBe('function');
    expect(typeof adapter.savePolicy).toBe('function');
    expect(typeof adapter.snapshot).toBe('function');
  });

  it('delegates predict/trainBatch to the linear impl', async () => {
    const adapter = await createPolicy({ type: 'linear' });
    adapter.predict([0, 0, 1], [1, 1, 1]);
    adapter.trainBatch([], [0, 0, 1], { learningRate: 0.05 });
    expect(linear.predict).toHaveBeenCalledWith([0, 0, 1], [1, 1, 1]);
    expect(linear.trainBatch).toHaveBeenCalledTimes(1);
  });
});

describe('createPolicy — explicit mlp', () => {
  it('builds an mlp adapter when type="mlp"', async () => {
    const adapter = await createPolicy({ type: 'mlp' });
    expect(adapter.type).toBe('mlp');
    expect(adapter.modelType).toBe('mlp');
    expect(typeof adapter.predict).toBe('function');
    expect(typeof adapter.trainBatch).toBe('function');
    expect(typeof adapter.evaluatePolicy).toBe('function');
    expect(typeof adapter.savePolicy).toBe('function');
    expect(typeof adapter.snapshot).toBe('function');
  });
});

describe('createPolicy — unknown type fallback', () => {
  it('falls back to linear and logs a warning', async () => {
    const log = makeLogger();
    const adapter = await createPolicy({ type: 'quantum', logger: log });
    expect(adapter.type).toBe('linear');
    expect(log.warn).toHaveBeenCalledTimes(1);
    expect(log.warn.mock.calls[0][0]).toMatch(/unknown modelType/i);
  });

  it('respects config.modelType when explicit type is omitted', async () => {
    const adapter = await createPolicy({ config: { modelType: 'mlp' } });
    expect(adapter.type).toBe('mlp');
  });

  it('prefers explicit type over config.modelType', async () => {
    const adapter = await createPolicy({
      type: 'linear',
      config: { modelType: 'mlp' },
    });
    expect(adapter.type).toBe('linear');
  });

  it('does not warn when config.modelType is a recognized value', async () => {
    const log = makeLogger();
    const adapter = await createPolicy({ config: { modelType: 'linear' }, logger: log });
    expect(adapter.type).toBe('linear');
    expect(log.warn).not.toHaveBeenCalled();
  });
});

describe('createPolicyFromFile', () => {
  it('uses modelType from an existing policy file', async () => {
    linear.loadPolicy.mockResolvedValueOnce({
      modelType: 'mlp',
      theta: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    });
    const result = await createPolicyFromFile({ policyPath: '/tmp/p.json' });
    expect(result.modelType).toBe('mlp');
    expect(result.adapter.type).toBe('mlp');
    expect(result.policy).toBeTruthy();
  });

  it('treats legacy "logistic-regression" modelType as linear', async () => {
    linear.loadPolicy.mockResolvedValueOnce({
      modelType: 'logistic-regression',
      theta: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    });
    const result = await createPolicyFromFile({ policyPath: '/tmp/p.json' });
    expect(result.modelType).toBe('linear');
    expect(result.adapter.type).toBe('linear');
  });

  it('falls back to linear when file is missing and no fallbackType set', async () => {
    linear.loadPolicy.mockResolvedValueOnce(null);
    const result = await createPolicyFromFile({ policyPath: '/tmp/missing.json' });
    expect(result.modelType).toBe('linear');
    expect(result.adapter.type).toBe('linear');
    expect(result.policy).toBeNull();
  });

  it('honors fallbackType when file is missing', async () => {
    linear.loadPolicy.mockResolvedValueOnce(null);
    const result = await createPolicyFromFile({
      policyPath: '/tmp/missing.json',
      fallbackType: 'mlp',
    });
    expect(result.modelType).toBe('mlp');
    expect(result.adapter.type).toBe('mlp');
  });

  it('treats legacy policy file (no modelType field) as linear', async () => {
    linear.loadPolicy.mockResolvedValueOnce({
      theta: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
      trainedAt: '2026-01-01T00:00:00.000Z',
    });
    const result = await createPolicyFromFile({ policyPath: '/tmp/legacy.json' });
    expect(result.modelType).toBe('linear');
    expect(result.adapter.type).toBe('linear');
    expect(result.policy).toEqual(
      expect.objectContaining({ theta: expect.any(Array) }),
    );
  });

  it('recovers gracefully when loadPolicy throws', async () => {
    linear.loadPolicy.mockRejectedValueOnce(new Error('disk fail'));
    const log = makeLogger();
    const result = await createPolicyFromFile({
      policyPath: '/tmp/broken.json',
      logger: log,
    });
    expect(result.policy).toBeNull();
    expect(result.adapter.type).toBe('linear');
    expect(log.warn).toHaveBeenCalled();
  });
});

describe('cleanup', () => {
  it('removes the test-only shim if we created one', () => {
    if (createdShim && fs.existsSync(NEURAL_POLICY_PATH)) {
      const content = fs.readFileSync(NEURAL_POLICY_PATH, 'utf8');
      if (content.includes('Test-only shim autogenerated')) {
        fs.unlinkSync(NEURAL_POLICY_PATH);
      }
    }
    expect(true).toBe(true);
  });
});
