/**
 * T-43 — `/doctor` Check 8 and Check 9.
 *
 * ── What these tests DO establish ─────────────────────────────────────────
 * That the pure judgement functions return the verdict the design specifies
 * for a hand-built input, that `unmeasured` is returned wherever an input was
 * not supplied, that the ten Check 9 items match Hardening §32 line for line,
 * and that adding the two sections left Checks 1-7 of `commands/doctor.md`
 * byte-identical to HEAD.
 *
 * ── What they CANNOT establish (§9 — state it next to the gate) ───────────
 * - **Anything about a live ledger.** Every fixture here is hand-built and
 *   tiny. Zero real `ledger.jsonl` records were read, so nothing here says the
 *   check behaves the same against a production-sized store, and the
 *   fixture-size trap applies in full: these inputs are single-digit records
 *   where a real store is unbounded.
 * - **That `/doctor` was ever run.** `commands/doctor.md` is a markdown command
 *   read by the model, not code this suite can execute. These tests assert the
 *   document says what it should and that the functions it names behave; they
 *   do NOT assert that any run of `/doctor` calls them, and no such run has
 *   been observed.
 * - **That the caller wires the inputs correctly.** The functions are pure and
 *   the reading half lives in the command prose. A command that reads the wrong
 *   file would still produce green tests here.
 * - **That the ten items are individually correct against a real project.**
 *   Each item is exercised by one passing and one failing fixture, which fixes
 *   the contract, not the field accuracy.
 */

import { describe, expect, it } from 'vitest';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ARTIFACT_HEALTH_ITEMS,
  ARTIFACT_HEALTH_SOURCE,
  checkArtifactHealth,
  checkLedgerStateParity,
  checkStateVersionGaps,
  CheckStatus,
  STALE_STATE,
  worstOf,
} from '../../lib/project-state/doctor-checks.js';
import { classifyStaleness, StaleState } from '../../lib/runtime/artifact-lifecycle.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PLUGIN_ROOT = path.resolve(HERE, '..', '..');
const REPO_ROOT = path.resolve(PLUGIN_ROOT, '..', '..');
const DOCTOR_MD = path.join(PLUGIN_ROOT, 'commands', 'doctor.md');
const CHECKS_JS = path.join(PLUGIN_ROOT, 'lib', 'project-state', 'doctor-checks.js');

const MID = 'M-20260902-001';
const TS = '2026-09-02T00:00:00.000Z';

/** A store journal record carrying a whole mission. */
const missionRecord = (state_version, mission) => ({
  v: 1, ts: TS, state_version, kind: 'mission.upsert', mission_id: MID, mission,
});

/**
 * The automatic `graph.upsert` a mission's FIRST commit writes beside its
 * `mission.upsert` (`lib/project-state/state-manager.js#updateMission`). Both
 * records carry the same `state_version`, because that number counts commits.
 */
const graphRecord = (state_version) => ({
  v: 1, ts: TS, state_version, kind: 'graph.upsert', mission_id: MID,
  graph: { schema_version: 1, mission_id: MID, tasks: [] },
});

/** The `state.updated` event the store pairs with each committed write. */
const stateUpdated = (state_version) => ({
  event: 'state.updated', mission_id: MID, session_id: 's', source: 'test', ts: TS,
  data: { state_version, status: 'executing', reason: 'test' },
});

const MISSION = {
  status: 'executing',
  intent: { path: 'i', revision: 1 },
  plan: { path: 'p', revision: 1 },
};

/**
 * The projection the fixture journal must fold back into, written out by hand
 * rather than produced by the code under test — a projection generated by the
 * same fold it is compared against would assert nothing.
 */
const EXPECTED_PROJECTION = {
  project: 'artibot',
  state_version: 1,
  updated_at: TS,
  active_missions: {
    [MID]: {
      status: 'executing',
      intent: { path: 'i', revision: 1 },
      plan: { path: 'p', revision: 1 },
      workers: {},
      blocked_by: [],
    },
  },
};

const codes = (result) => result.findings.map((f) => f.code);
const itemCodes = (result, key) => result.items[key].findings.map((f) => f.code);

// ---------------------------------------------------------------------------
// Purity and the copied vocabulary
// ---------------------------------------------------------------------------

describe('the judgement module performs no I/O', () => {
  it('names no filesystem module in its own source', () => {
    const source = readFileSync(CHECKS_JS, 'utf-8');
    const importLines = source.split('\n').filter((l) => /^import /.test(l));
    expect(importLines.join('\n')).not.toMatch(/node:fs/);
    expect(source).not.toMatch(/from ['"]node:fs['"]/);
    expect(source).not.toMatch(/require\(['"]node:fs['"]\)/);
  });

  it('imports nothing from the runtime layer, which L2 may not reach', () => {
    const source = readFileSync(CHECKS_JS, 'utf-8');
    expect(source).not.toMatch(/from ['"][^'"]*\/runtime\//);
  });
});

describe('STALE_STATE is a copy of T-40 vocabulary and must not drift', () => {
  it('equals the exported StaleState of lib/runtime/artifact-lifecycle.js', () => {
    // The copy exists because eslint blocks an L2 -> L5 import (design §1-8).
    // Tests carry no layer restriction, so the drift is caught here instead.
    expect({ ...STALE_STATE }).toEqual({ ...StaleState });
  });
});

describe('worstOf ranks unmeasured above pass', () => {
  it('never lets an unmeasured item summarise as healthy', () => {
    expect(worstOf(['pass', 'pass', 'unmeasured'])).toBe(CheckStatus.UNMEASURED);
    expect(worstOf(['pass', 'unmeasured', 'warn'])).toBe(CheckStatus.WARN);
    expect(worstOf(['warn', 'fail', 'unmeasured'])).toBe(CheckStatus.FAIL);
    expect(worstOf([])).toBe(CheckStatus.PASS);
  });
});

// ---------------------------------------------------------------------------
// Check 8 — parity
// ---------------------------------------------------------------------------

describe('checkLedgerStateParity — the journal still reproduces state.yaml', () => {
  it('passes when the fold reproduces the projection and every version is paired', () => {
    const result = checkLedgerStateParity({
      events: [stateUpdated(1)],
      journal: [missionRecord(1, MISSION)],
      projection: EXPECTED_PROJECTION,
    });
    expect(result.status).toBe(CheckStatus.PASS);
    expect(result.findings).toEqual([]);
  });

  it('fails when the projection on disk disagrees with the rebuild', () => {
    const drifted = {
      ...EXPECTED_PROJECTION,
      active_missions: { [MID]: { ...EXPECTED_PROJECTION.active_missions[MID], status: 'completed' } },
    };
    const result = checkLedgerStateParity({
      events: [stateUpdated(1)],
      journal: [missionRecord(1, MISSION)],
      projection: drifted,
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(codes(result)).toContain('projection-drift');
    expect(result.findings[0].comparison).toBe('structural');
  });

  it('compares raw text byte for byte, which is the design rule', () => {
    const result = checkLedgerStateParity({
      events: [stateUpdated(1)],
      journal: [missionRecord(1, MISSION)],
      projection: 'project: artibot\n',
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(result.findings[0].comparison).toBe('bytes');
  });

  it('fails on a store version with no paired event — the invariant broken', () => {
    const result = checkLedgerStateParity({
      events: [],
      journal: [missionRecord(1, MISSION)],
      projection: EXPECTED_PROJECTION,
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(codes(result)).toContain('ledger-subset-violation');
  });

  it('only warns when the store is behind the ledger — the invariant holds', () => {
    const result = checkLedgerStateParity({
      events: [stateUpdated(1), stateUpdated(2)],
      journal: [missionRecord(1, MISSION)],
      projection: EXPECTED_PROJECTION,
    });
    expect(result.status).toBe(CheckStatus.WARN);
    expect(codes(result)).toContain('store-behind-ledger');
    expect(codes(result)).not.toContain('ledger-subset-violation');
  });

  it.each([
    ['events', { journal: [], projection: EXPECTED_PROJECTION }, 'events (ledger)'],
    ['journal', { events: [], projection: EXPECTED_PROJECTION }, 'journal (store)'],
    ['projection', { events: [], journal: [] }, 'projection (state.yaml)'],
  ])('reports unmeasured, not pass, when %s was not read', (_name, input, absent) => {
    const result = checkLedgerStateParity(input);
    expect(result.status).toBe(CheckStatus.UNMEASURED);
    expect(result.findings[0].absent).toContain(absent);
  });

  it('distinguishes an empty-but-read store from a store never read', () => {
    const read = checkLedgerStateParity({
      events: [], journal: [], projection: { project: 'artibot', state_version: 0, active_missions: {} },
    });
    expect(read.status).toBe(CheckStatus.PASS);
    expect(checkLedgerStateParity({}).status).toBe(CheckStatus.UNMEASURED);
  });
});

// ---------------------------------------------------------------------------
// Check 8 — the reader's line census (F-30)
// ---------------------------------------------------------------------------

describe('checkLedgerStateParity — the ledger line census', () => {
  // A census in the shape `lib/runtime/ledger.js#readLedgerCensus` returns, hand-built
  // and INDEPENDENT of the parity `events` beside it (`survivors === events.length` is
  // tests/runtime/ledger.test.js's contract; `checkLedgerStateParity` never cross-checks).
  const census = (loss, selection = { rejected_excluded: 0, filtered_out: 0 }) => ({
    file: { present: true, readable: true, bytes: 10, path: '/tree/.artibot/runtime/ledger.jsonl' },
    lines: { raw: 4, blank: 1, nonblank: 3 },
    dropped: { loss, selection },
    survivors: 3 - Object.values(loss).reduce((a, b) => a + b, 0)
      - Object.values(selection).reduce((a, b) => a + b, 0),
    dropped_total: {
      loss: Object.values(loss).reduce((a, b) => a + b, 0),
      selection: Object.values(selection).reduce((a, b) => a + b, 0),
    },
  });
  const healthy = {
    events: [stateUpdated(1)], journal: [missionRecord(1, MISSION)], projection: EXPECTED_PROJECTION,
  };

  it('reports census as unmeasured when none was supplied — and does NOT demote the check', () => {
    // `worstOf` ranks unmeasured above pass: in `findings` this would demote every caller.
    const result = checkLedgerStateParity(healthy);
    expect(result.status).toBe(CheckStatus.PASS);
    expect(result.findings).toEqual([]);
    expect(result.census.status).toBe(CheckStatus.UNMEASURED);
    expect(result.census.reason).toMatch(/not counted/);
  });

  it('carries the census verdict even when the parity inputs were absent', () => {
    const result = checkLedgerStateParity({});
    expect(result.status).toBe(CheckStatus.UNMEASURED);
    expect(result.census.status).toBe(CheckStatus.UNMEASURED);
  });

  it('passes the census when the reader counted zero loss', () => {
    const result = checkLedgerStateParity({
      ...healthy, census: census({ corrupt: 0, malformed_envelope: 0, duplicate: 0 }),
    });
    expect(result.status).toBe(CheckStatus.PASS);
    expect(result.findings).toEqual([]);
    expect(result.census).toMatchObject({
      status: CheckStatus.PASS,
      loss: { corrupt: 0, malformed_envelope: 0, duplicate: 0 },
      path: '/tree/.artibot/runtime/ledger.jsonl',
    });
  });

  it('warns with ledger-lines-dropped when the reader counted any loss', () => {
    const result = checkLedgerStateParity({
      ...healthy, census: census({ corrupt: 1, malformed_envelope: 0, duplicate: 1 }),
    });
    expect(result.status).toBe(CheckStatus.WARN);
    expect(codes(result)).toEqual(['ledger-lines-dropped']);
    const finding = result.findings[0];
    expect(finding.status).toBe(CheckStatus.WARN);
    expect(finding.loss).toEqual({ corrupt: 1, malformed_envelope: 0, duplicate: 1 });
    expect(finding.path).toBe('/tree/.artibot/runtime/ledger.jsonl');
    expect(finding.detail).toMatch(/2 damaged line\(s\) of 3/);
    expect(result.census.status).toBe(CheckStatus.WARN);
  });

  it('does not warn on selection drops — those are the caller\'s own filters', () => {
    const result = checkLedgerStateParity({
      ...healthy,
      census: census(
        { corrupt: 0, malformed_envelope: 0, duplicate: 0 },
        { rejected_excluded: 2, filtered_out: 1 },
      ),
    });
    expect(result.status).toBe(CheckStatus.PASS);
    expect(result.findings).toEqual([]);
    expect(result.census.selection).toEqual({ rejected_excluded: 2, filtered_out: 1 });
  });

  it('never lets a census loss outrank a parity failure', () => {
    const result = checkLedgerStateParity({
      events: [], journal: [missionRecord(1, MISSION)], projection: EXPECTED_PROJECTION,
      census: census({ corrupt: 1, malformed_envelope: 0, duplicate: 0 }),
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(codes(result)).toEqual(expect.arrayContaining(['ledger-subset-violation', 'ledger-lines-dropped']));
  });

  it('treats a census without the F-30 shape as unmeasured, not as zero loss', () => {
    const bads = [
      null, 'census', 42, {}, { dropped_total: { loss: 'x' } },
      { dropped_total: { loss: 1, selection: 0 }, dropped: { loss: 'xy', selection: 'z' } }, // truthy, not a shape
      { dropped_total: { loss: 0, selection: 0 }, dropped: { loss: { corrupt: 0 }, selection: {} } },
      { ...census({ corrupt: 1, malformed_envelope: 0, duplicate: 0 }), lines: undefined }, // no denominator
    ];
    for (const bad of bads) {
      const result = checkLedgerStateParity({ ...healthy, census: bad });
      expect(result.status, JSON.stringify(bad)).toBe(CheckStatus.PASS);
      expect(result.findings, JSON.stringify(bad)).toEqual([]);
      expect(result.census.status, JSON.stringify(bad)).toBe(CheckStatus.UNMEASURED);
      expect(result.census.loss).toBeUndefined();
    }
  });

  it('reports an absent or unreadable ledger file as unmeasured, never as a clean pass', () => {
    // A missing file's census is all zeros and fully shaped; `pass` there would
    // make "no ledger" read as "clean ledger" — the confusion the census exists to end.
    const absent = {
      ...census({ corrupt: 0, malformed_envelope: 0, duplicate: 0 }),
      file: { present: false, readable: false, bytes: null, path: '/tree/.artibot/runtime/ledger.jsonl' },
      lines: { raw: 0, blank: 0, nonblank: 0 }, survivors: 0,
    };
    const result = checkLedgerStateParity({ ...healthy, census: absent });
    expect(result.status).toBe(CheckStatus.PASS);
    expect(result.findings).toEqual([]);
    expect(result.census).toMatchObject({
      status: CheckStatus.UNMEASURED,
      file: { present: false, readable: false },
      path: '/tree/.artibot/runtime/ledger.jsonl',
    });
    expect(result.census.reason).toMatch(/absent/);

    const unreadable = { ...absent, file: { ...absent.file, present: true } };
    const r2 = checkLedgerStateParity({ ...healthy, census: unreadable });
    expect(r2.census.status).toBe(CheckStatus.UNMEASURED);
    expect(r2.census.reason).toMatch(/unreadable/);

    // And a present, readable, empty ledger IS a counted zero.
    const empty = { ...absent, file: { ...absent.file, present: true, readable: true, bytes: 0 } };
    expect(checkLedgerStateParity({ ...healthy, census: empty }).census.status).toBe(CheckStatus.PASS);
  });

  it('the Check 8 prose names the loss row and the unmeasured rule', () => {
    const section = checkSections(CURRENT).get('Check 8');
    expect(section).toContain('readLedgerCensus(projectRoot)');
    expect(section).toMatch(/`census\.dropped_total\.loss > 0`.*\*\*warn\*\*/);
    expect(section).toMatch(/census not supplied = unmeasured/);
  });
});

// ---------------------------------------------------------------------------
// Check 8 — the version counter
// ---------------------------------------------------------------------------

describe('checkStateVersionGaps — holes, regressions and duplicates', () => {
  it('passes on an unbroken sequence', () => {
    const result = checkStateVersionGaps({
      journal: [1, 2, 3].map((v) => missionRecord(v, MISSION)),
    });
    expect(result.status).toBe(CheckStatus.PASS);
    expect(result.gaps).toEqual([]);
    expect(result.versions).toEqual([1, 2, 3]);
  });

  it('enumerates every missing number, not just the first', () => {
    const result = checkStateVersionGaps({
      journal: [1, 4].map((v) => missionRecord(v, MISSION)),
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(result.gaps).toEqual([2, 3]);
    expect(codes(result)).toContain('state-version-gap');
  });

  it('reports a version that goes backwards', () => {
    const result = checkStateVersionGaps({
      journal: [1, 2, 3, 2].map((v) => missionRecord(v, MISSION)),
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(codes(result)).toContain('state-version-regression');
    expect(result.regressions).toEqual([{ index: 3, version: 2, after: 3 }]);
  });

  // REPAIRED 2026-09-05. This case was `journal: [1, 2, 2]`, and its meaning
  // changed under the transaction fold: two CONSECUTIVE records at version 2 are
  // now read as the one commit that wrote both, so the old fixture passes. The
  // original intent — one CAS slot claimed by two separate writes — survives only
  // as a NON-CONTIGUOUS reappearance, so version 2 is reclaimed after version 3.
  // The fixture it now shares with the regression case above is deliberate: a
  // reappearance out of run is necessarily also a regression, and the two tests
  // assert different halves of that.
  it('reports two transactions claiming one version — one CAS slot, two writes', () => {
    const result = checkStateVersionGaps({
      journal: [1, 2, 3, 2].map((v) => missionRecord(v, MISSION)),
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(result.duplicates).toEqual([2]);
    expect(codes(result)).toContain('state-version-duplicate');
  });

  // ---- the transaction fold -------------------------------------------------
  // `state_version` counts COMMITS, not records. `state-manager.js#commitLocked`
  // stamps every record of one commit with the same number, and
  // `state-manager.js#updateMission` writes TWO records on a mission's first
  // commit (`mission.upsert` plus an automatic `graph.upsert`). Measured against a
  // live store 2026-09-05 09:13 KST: one `updateMission` on an empty project root
  // wrote `mission.upsert@v1 | graph.upsert@v1`, and the per-record scan called
  // that healthy store `fail` / `duplicates: [1]` on its very first write.

  it('passes a commit that wrote two records under one version', () => {
    const result = checkStateVersionGaps({
      journal: [missionRecord(1, MISSION), graphRecord(1), missionRecord(2, MISSION)],
    });
    expect(result.status).toBe(CheckStatus.PASS);
    expect(result.duplicates).toEqual([]);
    expect(result.findings).toEqual([]);
    // `versions` stays the RAW per-record list — only the judgement folds, so the
    // caller can still see how many records each commit wrote.
    expect(result.versions).toEqual([1, 1, 2]);
  });

  it('passes a run of any length, so a wide commit is not a duplicate', () => {
    const result = checkStateVersionGaps({
      journal: [1, 1, 2, 2, 2, 3].map((v) => missionRecord(v, MISSION)),
    });
    expect(result.status).toBe(CheckStatus.PASS);
    expect(result.duplicates).toEqual([]);
    expect(result.gaps).toEqual([]);
  });

  it('still fails a version that reappears after another — the fold keeps that visible', () => {
    const result = checkStateVersionGaps({
      journal: [1, 2, 1].map((v) => missionRecord(v, MISSION)),
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(result.duplicates).toEqual([1]);
    // Measured, not assumed: the regression finding is reported ALONGSIDE the
    // duplicate. After the fold `state-version-duplicate` can never stand alone,
    // because a version can only reappear out of run if a different version sat
    // between its two runs.
    expect(codes(result)).toEqual(['state-version-regression', 'state-version-duplicate']);
    expect(result.regressions).toEqual([{ index: 2, version: 1, after: 2 }]);
  });

  it('still finds a hole across a folded run — the fold must not hide a gap', () => {
    const result = checkStateVersionGaps({
      journal: [1, 1, 3].map((v) => missionRecord(v, MISSION)),
    });
    expect(result.status).toBe(CheckStatus.FAIL);
    expect(result.gaps).toEqual([2]);
    expect(result.duplicates).toEqual([]);
    expect(codes(result)).toEqual(['state-version-gap']);
  });

  it('warns when records exist but none carries a version', () => {
    const result = checkStateVersionGaps({ journal: [{ kind: 'meta.upsert' }] });
    expect(result.status).toBe(CheckStatus.WARN);
    expect(codes(result)).toContain('no-versioned-records');
  });

  it('is unmeasured when no journal was supplied', () => {
    expect(checkStateVersionGaps({}).status).toBe(CheckStatus.UNMEASURED);
    expect(checkStateVersionGaps({ journal: [] }).status).toBe(CheckStatus.PASS);
  });
});

// ---------------------------------------------------------------------------
// Check 9 — the ten items of Hardening §32
// ---------------------------------------------------------------------------

/** A mission whose four artifacts are all present and mutually current. */
const healthyMission = (over = {}) => ({
  mission_id: MID,
  files: {
    intent: { revision: 2, schema_version: 1 },
    plan: { revision: 3, schema_version: 1, based_on: { intent_revision: 2 } },
    review: { revision: 1, schema_version: 1, based_on: { intent_revision: 2, plan_revision: 3 } },
    outcome: {
      revision: 1, schema_version: 1,
      based_on: { intent_revision: 2, plan_revision: 3, review_revision: 1 },
    },
  },
  ...over,
});

/** Every input supplied, so all ten items are measured. */
const fullyMeasured = (missions) => ({
  missionDirs: missions,
  classifyStaleness,
  activeMissionIds: [MID],
  leases: {},
  now: '2026-09-02T12:00:00.000Z',
  parity: { status: CheckStatus.PASS, findings: [] },
  evidenceIds: ['E-001'],
  supportedSchemaVersions: [1],
});

describe('checkArtifactHealth — the ten §32 items', () => {
  it('carries all ten items, keyed in document order, each citing its line', () => {
    const keys = Object.keys(ARTIFACT_HEALTH_ITEMS);
    expect(keys).toEqual([
      'missing_intent', 'broken_based_on', 'stale_plan', 'invalid_review',
      'duplicate_canonical_artifact', 'orphan_mission', 'expired_task_lease',
      'ledger_state_mismatch', 'missing_evidence_reference', 'unsupported_schema_version',
    ]);
    expect(keys).toHaveLength(10);
    const lines = keys.map((k) => Number(ARTIFACT_HEALTH_ITEMS[k].match(/:(\d+) /)[1]));
    expect(lines).toEqual([994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003]);
  });

  it('passes all ten when every input is supplied and nothing is wrong', () => {
    const result = checkArtifactHealth(fullyMeasured([
      { ...healthyMission(), extraFiles: ['notes.md'] },
    ]));
    expect(result.status).toBe(CheckStatus.PASS);
    expect(Object.values(result.items).every((i) => i.status === CheckStatus.PASS)).toBe(true);
    expect(result.findings).toEqual([]);
  });

  it('reports every item unmeasured when no mission folder was read', () => {
    const result = checkArtifactHealth({});
    expect(result.status).toBe(CheckStatus.UNMEASURED);
    expect(Object.values(result.items)).toHaveLength(10);
    for (const entry of Object.values(result.items)) {
      expect(entry.status).toBe(CheckStatus.UNMEASURED);
    }
  });

  it('summarises as unmeasured when some items ran and others did not', () => {
    const result = checkArtifactHealth({ missionDirs: [healthyMission()] });
    expect(result.items.missing_intent.status).toBe(CheckStatus.PASS);
    expect(result.items.orphan_mission.status).toBe(CheckStatus.UNMEASURED);
    expect(result.status).toBe(CheckStatus.UNMEASURED);
  });

  // -- item 1 --------------------------------------------------------------
  it('item 1 fails on a mission folder with no intent.md', () => {
    const m = healthyMission();
    m.files.intent = null;
    const result = checkArtifactHealth(fullyMeasured([m]));
    expect(result.items.missing_intent.status).toBe(CheckStatus.FAIL);
    expect(itemCodes(result, 'missing_intent')).toEqual(['missing-intent']);
  });

  // -- items 2, 3, 4 -------------------------------------------------------
  it('item 2 fails on a based_on claiming a revision the mission never reached', () => {
    const m = healthyMission();
    m.files.plan.based_on = { intent_revision: 99 };
    const result = checkArtifactHealth(fullyMeasured([m]));
    expect(result.items.broken_based_on.status).toBe(CheckStatus.FAIL);
    expect(result.items.broken_based_on.findings[0].state).toBe(STALE_STATE.BROKEN);
  });

  it('item 3 fails on a plan built against a superseded intent', () => {
    const m = healthyMission();
    m.files.plan.based_on = { intent_revision: 1 };
    const result = checkArtifactHealth(fullyMeasured([m]));
    expect(result.items.stale_plan.status).toBe(CheckStatus.FAIL);
    expect(result.items.stale_plan.findings[0].state).toBe(STALE_STATE.STALE);
  });

  it('item 4 fails on a review built against a superseded plan', () => {
    const m = healthyMission();
    m.files.review.based_on = { intent_revision: 2, plan_revision: 2 };
    const result = checkArtifactHealth(fullyMeasured([m]));
    expect(result.items.invalid_review.status).toBe(CheckStatus.FAIL);
    expect(result.items.invalid_review.findings[0].state).toBe(STALE_STATE.INVALID);
  });

  it('items 2-4 are unmeasured when the staleness port is not injected', () => {
    const result = checkArtifactHealth({ missionDirs: [healthyMission()] });
    for (const key of ['broken_based_on', 'stale_plan', 'invalid_review']) {
      expect(result.items[key].status).toBe(CheckStatus.UNMEASURED);
    }
  });

  it('carries a NOT_ACCEPTABLE outcome outside the ten, never inside one', () => {
    const m = healthyMission();
    m.files.outcome.based_on = { intent_revision: 2, plan_revision: 3, review_revision: 0 };
    const result = checkArtifactHealth(fullyMeasured([m]));
    expect(result.findings[0].code).toBe('outcome-not-acceptable');
    expect(result.findings[0].outsideCanonicalTen).toBe(true);
    expect(result.status).toBe(CheckStatus.FAIL);
  });

  // -- item 5 --------------------------------------------------------------
  it('item 5 fails on a file competing with a canonical artifact', () => {
    const result = checkArtifactHealth(fullyMeasured([
      { ...healthyMission(), extraFiles: ['plan2.md'] },
    ]));
    expect(result.items.duplicate_canonical_artifact.status).toBe(CheckStatus.FAIL);
    expect(result.items.duplicate_canonical_artifact.findings[0].file).toBe('plan2.md');
  });

  it('item 5 is unmeasured when no folder listing was supplied', () => {
    const result = checkArtifactHealth(fullyMeasured([healthyMission()]));
    expect(result.items.duplicate_canonical_artifact.status).toBe(CheckStatus.UNMEASURED);
  });

  // -- item 6 --------------------------------------------------------------
  it('item 6 fails on a mission absent from the live state with no outcome', () => {
    const m = healthyMission();
    m.files.outcome = null;
    const result = checkArtifactHealth({ ...fullyMeasured([m]), activeMissionIds: [] });
    expect(result.items.orphan_mission.status).toBe(CheckStatus.FAIL);
  });

  it('item 6 passes a closed mission — absent from the live state but with an outcome', () => {
    const result = checkArtifactHealth({
      ...fullyMeasured([healthyMission()]), activeMissionIds: [],
    });
    expect(result.items.orphan_mission.status).toBe(CheckStatus.PASS);
  });

  // -- item 7 --------------------------------------------------------------
  it('item 7 fails on a lease whose expiry has passed', () => {
    const result = checkArtifactHealth({
      ...fullyMeasured([healthyMission()]),
      leases: { [MID]: { 't1': { owner: 'w', expires_at: '2026-09-02T11:00:00.000Z' } } },
    });
    expect(result.items.expired_task_lease.status).toBe(CheckStatus.FAIL);
    expect(result.items.expired_task_lease.findings[0].task_id).toBe('t1');
  });

  it('item 7 is unmeasured without a readable now', () => {
    const result = checkArtifactHealth({
      ...fullyMeasured([healthyMission()]), now: undefined,
    });
    expect(result.items.expired_task_lease.status).toBe(CheckStatus.UNMEASURED);
  });

  // -- item 8 --------------------------------------------------------------
  it('item 8 reports the Check 8 verdict rather than recomputing it', () => {
    const parity = { status: CheckStatus.FAIL, findings: [{ code: 'state-version-gap' }] };
    const result = checkArtifactHealth({ ...fullyMeasured([healthyMission()]), parity });
    expect(result.items.ledger_state_mismatch.status).toBe(CheckStatus.FAIL);
    expect(itemCodes(result, 'ledger_state_mismatch')).toEqual(['state-version-gap']);
  });

  it('item 8 is unmeasured when no parity result was passed in', () => {
    const result = checkArtifactHealth({
      ...fullyMeasured([healthyMission()]), parity: undefined,
    });
    expect(result.items.ledger_state_mismatch.status).toBe(CheckStatus.UNMEASURED);
  });

  // -- item 9 --------------------------------------------------------------
  it('item 9 fails on an evidence id the registry does not hold', () => {
    const m = healthyMission();
    m.files.plan.evidence_refs = ['E-001', 'E-404'];
    const result = checkArtifactHealth(fullyMeasured([m]));
    expect(result.items.missing_evidence_reference.status).toBe(CheckStatus.FAIL);
    expect(result.items.missing_evidence_reference.findings[0].ref).toBe('E-404');
  });

  it('item 9 is unmeasured without a registry to resolve against', () => {
    const result = checkArtifactHealth({
      ...fullyMeasured([healthyMission()]), evidenceIds: undefined,
    });
    expect(result.items.missing_evidence_reference.status).toBe(CheckStatus.UNMEASURED);
  });

  // -- item 10 -------------------------------------------------------------
  it('item 10 fails on a schema version this build cannot read', () => {
    const m = healthyMission();
    m.files.review.schema_version = 7;
    const result = checkArtifactHealth(fullyMeasured([m]));
    expect(result.items.unsupported_schema_version.status).toBe(CheckStatus.FAIL);
    expect(result.items.unsupported_schema_version.findings[0].declared).toBe(7);
  });

  it('item 10 fails an artifact that declares no version at all', () => {
    const m = healthyMission();
    delete m.files.outcome.schema_version;
    const result = checkArtifactHealth(fullyMeasured([m]));
    expect(result.items.unsupported_schema_version.status).toBe(CheckStatus.FAIL);
    expect(result.items.unsupported_schema_version.findings[0].declared).toBeNull();
  });
});

describe('the cited canon is the tracked copy (OD-3)', () => {
  // Enforced rather than commented: `/docs/` is gitignored (.gitignore:19), so
  // a citation that drifts back there names a path absent from a fresh clone
  // and the reader has nothing to open. A prose note would not have caught it.
  it('points at a file that actually exists in the repo', () => {
    expect(existsSync(path.join(REPO_ROOT, ARTIFACT_HEALTH_SOURCE))).toBe(true);
  });

  it('does not cite the ignored docs/ copy', () => {
    expect(ARTIFACT_HEALTH_SOURCE.startsWith('docs/')).toBe(false);
    expect(ARTIFACT_HEALTH_SOURCE).toBe('.artibot/guides/v5-design/ADDENDUM-HARDENING.md');
  });

  it('still finds the ten items at the lines each entry claims', () => {
    const doc = readFileSync(path.join(REPO_ROOT, ARTIFACT_HEALTH_SOURCE), 'utf-8')
      .replace(/\r\n/g, '\n').split('\n');
    const expected = [
      'Missing intent.md', 'Broken based_on revision', 'Stale plan', 'Invalid review',
      'Duplicate canonical artifact', 'Orphan mission', 'Expired task lease',
      'Ledger/state mismatch', 'Missing evidence reference', 'Unsupported schema version',
    ];
    Object.values(ARTIFACT_HEALTH_ITEMS).forEach((citation, i) => {
      const line = Number(citation.match(/:(\d+) /)[1]);
      // `doc` is 0-indexed, the citation is 1-indexed.
      expect(doc[line - 1]).toBe(expected[i]);
    });
  });
});

// ---------------------------------------------------------------------------
// commands/doctor.md
// ---------------------------------------------------------------------------

/**
 * Split a command document into its `### Check N` blocks, each running to the
 * next heading of level 2 or 3.
 *
 * @param {string} md - Document text, newline-normalised.
 * @returns {Map<string, string>} Check label to block text.
 */
function checkSections(md) {
  const headings = [...md.matchAll(/^#{2,3} .*$/gm)];
  const out = new Map();
  headings.forEach((h, i) => {
    const label = h[0].match(/^### (Check \d+)/);
    if (label === null) return;
    const end = i + 1 < headings.length ? headings[i + 1].index : md.length;
    out.set(label[1], md.slice(h.index, end));
  });
  return out;
}

// The working file is CRLF and the git blob is LF (measured 2026-09-02:
// 515 LF, all 515 preceded by CR). Normalising compares content rather than
// the platform's line-ending convention, which is not what this gate is about.
const lf = (s) => s.replace(/\r\n/g, '\n');
const CURRENT = lf(readFileSync(DOCTOR_MD, 'utf-8'));
const HEAD = lf(execFileSync(
  'git', ['show', 'HEAD:plugins/artibot/commands/doctor.md'],
  { cwd: REPO_ROOT, encoding: 'utf-8', maxBuffer: 8 * 1024 * 1024 },
));

describe('commands/doctor.md gained Check 8 and Check 9', () => {
  it('carries both new sections', () => {
    expect(CURRENT).toMatch(/^### Check 8: Ledger \/ State Parity$/m);
    expect(CURRENT).toMatch(/^### Check 9: Artifact Health$/m);
  });

  it('offers a scope filter for each', () => {
    expect(CURRENT).toMatch(/^- `state`: Check 8 only/m);
    expect(CURRENT).toMatch(/^- `artifacts`: Check 9 only/m);
    expect(CURRENT).toMatch(/^- \(no argument\): Run all 10 checks$/m);
  });

  it('gained one output-format line per check', () => {
    expect(CURRENT).toMatch(/^\[check-8-icon] State parity: /m);
    expect(CURRENT).toMatch(/^\[check-9-icon] Artifacts: /m);
  });

  it('names the ten §32 items and their canonical source', () => {
    const section = checkSections(CURRENT).get('Check 9');
    expect(section).toContain('.artibot/guides/v5-design/ADDENDUM-HARDENING.md');
    expect(section).toContain('994-1003');
    for (const label of [
      'Missing intent.md', 'Broken based_on revision', 'Stale plan', 'Invalid review',
      'Duplicate canonical artifact', 'Orphan mission', 'Expired task lease',
      'Ledger/state mismatch', 'Missing evidence reference', 'Unsupported schema version',
    ]) {
      expect(section).toContain(label);
    }
  });

  it('states that neither new check is a --fix target', () => {
    const nine = checkSections(CURRENT).get('Check 9');
    expect(nine).toContain('not `--fix` targets');
  });

  it('leaves the self-heal section byte-identical to HEAD', () => {
    const slice = (md) => md.slice(md.indexOf('## Self-Heal'));
    expect(slice(CURRENT)).toBe(slice(HEAD));
  });
});

/**
 * SHA-256 of each Check 1-7 block as it stood at the commit T-43 branched from
 * (dc9a4c12, measured 2026-09-02). Frozen here rather than read from HEAD every
 * run for one reason: the moment the commit that lands T-43 is made, HEAD's
 * doctor.md contains Check 8 and Check 9, and a gate that compares against HEAD
 * would then be comparing this change against itself. A frozen digest keeps
 * asserting the same thing after the commit as before it.
 *
 * Changing a value here is only correct when Check 1-7 prose is DELIBERATELY
 * edited. Refreshing one to make a red test green is how a ratchet destroys its
 * own reference.
 *
 * Check 7 was re-frozen ONCE, on 2026-09-03, for a deliberate edit that had
 * nothing to do with T-43: the decision-event store moved from
 * `<pluginRoot>/runtime/decisions/` to `<projectRoot>/.artibot/runtime/decisions/`
 * (`lib/observability/decision-events.js#getDecisionStoreDir`), and Check 7 is
 * that store's only reader. Its text had to follow, because the two stores no
 * longer share a root and S6's stated rationale ("both under the same resolved
 * root") had become false. Checks 1-6 are untouched and still carry their
 * dc9a4c12 digests, which is what keeps this refresh auditable: a refresh that
 * moved all seven would prove nothing.
 *   66d45dd3e6cc4812 -> 68a73087845aa9cd
 *
 * Check 7 was re-frozen a SECOND time on 2026-09-05, for D9 — the decision-trail
 * freeze (`DESIGN-TRAIL-migration-projectRoot.md` §2 C, owner rulings TR-1..3):
 * the check now resolves ONE root (the project root), S6 is retired, the
 * plugin-root trail is an informational row, and `cron-` files are counted
 * apart from session files. Checks 1-6 still carry their dc9a4c12 digests.
 *   68a73087845aa9cd -> f9cbd1a65ef3c2cc
 */
const CHECK_1_7_SHA256 = Object.freeze({
  'Check 1': '68a7994da5db8345',
  'Check 2': 'abb2dcdb15ee2345',
  'Check 3': '13cf1d3e560e5b64',
  'Check 4': 'b48ec269f024a6d3',
  'Check 5': '76b677614892ac3c',
  'Check 6': '889cb2c477eae694',
  // Re-frozen 2026-09-03 (store path move) and 2026-09-05 (D9). See the note above.
  'Check 7': 'f9cbd1a65ef3c2cc',
});

// Truncated to 16 hex characters, the same shape `lib/core/skill-hash.js` uses
// for its own content digests. 64 bits is far past collision reach for seven
// fixed strings, and the full digest reads to a secret scanner as a credential.
const sha = (s) => createHash('sha256').update(s).digest('hex').slice(0, 16);

describe('Checks 1-7 were not touched', () => {
  const current = checkSections(CURRENT);

  it('still carries exactly seven original sections plus the three new ones', () => {
    expect([...current.keys()]).toHaveLength(10);
  });

  it.each([1, 2, 3, 4, 5, 6, 7])('keeps Check %i byte-identical to the frozen baseline', (n) => {
    const key = `Check ${n}`;
    expect(current.get(key)).toBeTypeOf('string');
    expect(sha(current.get(key))).toBe(CHECK_1_7_SHA256[key]);
  });

  it('keeps the six untouched output-format lines byte-identical', () => {
    for (let n = 1; n <= 6; n += 1) {
      const line = HEAD.split('\n').find((l) => l.startsWith(`[check-${n}-icon]`));
      expect(line).toBeTypeOf('string');
      expect(CURRENT).toContain(line);
    }
  });

  it('re-worded the Check 7 output line for D9 (one root, frozen trail)', () => {
    // Pinned as a literal, not against HEAD: the 2026-09-05 edit is deliberate
    // and this is the one line of the seven that was allowed to move.
    expect(CURRENT).toContain(
      '[check-7-icon] Explainability: {n} session event lines (24h), {n} cron files, '
      + 'trail legacy(frozen) {exists|absent}/{n}, last {timestamp}',
    );
  });
});

describe('the frozen baseline still matches git, while HEAD predates T-43', () => {
  // A second, independent witness for the pre-commit window. Once T-43 lands,
  // HEAD carries Check 8 and this comparison would grade the change against
  // itself, so it stands down and says so rather than asserting something
  // weaker under the same name.
  const headHasNewChecks = HEAD.includes('### Check 8');
  const head = checkSections(HEAD);

  it.skipIf(headHasNewChecks)('reads seven check sections at HEAD', () => {
    expect([...head.keys()]).toHaveLength(7);
  });

  it.skipIf(headHasNewChecks)('agrees with the frozen digests', () => {
    for (const [key, digest] of Object.entries(CHECK_1_7_SHA256)) {
      expect(sha(head.get(key))).toBe(digest);
    }
  });
});
