/**
 * Tests for scripts/gen-model-catalog-docs.js — the CLAUDE-MODEL-CATALOG.md
 * generator. The doc is GENERATED output; these tests pin the renderer so a
 * catalog data change cannot silently produce a stale or malformed doc.
 */
import { describe, expect, it } from 'vitest';

import * as catalog from '../../lib/core/model-catalog.js';
import { renderDoc, specTable, toFileUrl } from '../../scripts/gen-model-catalog-docs.js';

describe('gen-model-catalog-docs', () => {
  describe('toFileUrl', () => {
    it('builds file:/// URLs for Windows drive paths without percent-encoding', () => {
      const url = toFileUrl('C:\\Users\\nowhe\\바탕 화면\\AI\\artibot\\lib\\x.js');
      expect(url).toBe('file:///C:/Users/nowhe/바탕 화면/AI/artibot/lib/x.js');
      expect(url).not.toContain('%');
    });

    it('builds file:// URLs for POSIX paths', () => {
      expect(toFileUrl('/home/user/lib/x.js')).toBe('file:///home/user/lib/x.js');
    });
  });

  describe('specTable', () => {
    it('renders one row per catalog tier plus a 2-line header', () => {
      const lines = specTable(catalog);
      expect(lines.length).toBe(2 + catalog.listTiers().length);
    });

    it('includes every tier id from the catalog', () => {
      const body = specTable(catalog).join('\n');
      for (const tier of catalog.listTiers()) {
        expect(body).toContain(`\`${catalog.getModel(tier).id}\``);
      }
    });
  });

  describe('renderDoc', () => {
    const doc = renderDoc(catalog);

    it('carries the GENERATED do-not-hand-edit header', () => {
      expect(doc).toContain('GENERATED by scripts/gen-model-catalog-docs.js');
      expect(doc).toContain('lib/core/model-catalog.js');
    });

    it('documents the fable constraints from catalog data', () => {
      expect(doc).toContain('claude-fable-5');
      expect(doc).toContain('always-on');
      expect(doc).toContain('refusal');
      for (const key of catalog.getModel('fable').constraints) {
        expect(doc).toContain(key);
      }
    });

    it('derives the effective cost factor from the catalog (no hardcode drift)', () => {
      expect(doc).toContain(`~${catalog.getCostFactor('fable')}×`);
    });

    it('states the routing policy: fable is opt-in, default stays opus', () => {
      expect(doc).toContain('opt-in');
      expect(doc).toContain('Opus 4.8');
      expect(doc).toContain('deep-async→fable');
    });

    it('contains no stale "fable cannot be a subagent" phrasing', () => {
      expect(doc).not.toMatch(/cannot be a subagent tier/i);
      expect(doc).not.toMatch(/API-only/i);
    });
  });
});
