/**
 * Tests for scripts/gen-model-catalog-docs.js — the CLAUDE-MODEL-CATALOG.md
 * generator. The doc is GENERATED output; these tests pin the renderer so a
 * catalog data change cannot silently produce a stale or malformed doc.
 */
import { describe, expect, it } from 'vitest';

import * as catalog from '../../lib/core/model-catalog.js';
import { checkDoc, renderDoc, specTable, toFileUrl } from '../../scripts/gen-model-catalog-docs.js';

describe('gen-model-catalog-docs', () => {
  describe('checkDoc (--check mode, write-free)', () => {
    const rendered = renderDoc(catalog);

    it('reports match when disk equals the render', () => {
      expect(checkDoc(rendered, rendered)).toEqual({ upToDate: true, reason: 'match' });
    });

    it('treats a CRLF checkout of the same content as up to date', () => {
      expect(checkDoc(rendered, rendered.replace(/\n/g, '\r\n')).upToDate).toBe(true);
    });

    it('reports stale when content differs', () => {
      expect(checkDoc(rendered, rendered + '\nextra')).toEqual({ upToDate: false, reason: 'stale' });
    });

    it('reports missing when the doc is absent', () => {
      expect(checkDoc(rendered, null)).toEqual({ upToDate: false, reason: 'missing' });
    });
  });

  describe('fable heading', () => {
    it('derives the fable heading from the catalog id, with no hand-typed generation number', () => {
      const doc = renderDoc(catalog);
      const id = catalog.getModel('fable').id;
      expect(doc).toContain(`## Claude Fable (\`${id}\`)`);
      expect(doc).not.toMatch(/^## Claude Fable \d/m);
    });
  });

  describe('toFileUrl', () => {
    it('builds file:/// URLs for Windows drive paths without percent-encoding', () => {
      const url = toFileUrl('C:\\Users\\nowhe\\바탕 화면\\AI\\artibot\\lib\\x.js');
      expect(url).toBe('file:///C:/Users/nowhe/바탕 화면/AI/artibot/lib/x.js');
      expect(url).not.toContain('%');
    });

    it('builds file:// URLs for POSIX paths', () => {
      expect(toFileUrl('/home/user/lib/x.js')).toBe('file:///home/user/lib/x.js');
    });
  });

  describe('specTable', () => {
    it('renders one row per catalog tier plus a 2-line header', () => {
      const lines = specTable(catalog);
      expect(lines.length).toBe(2 + catalog.listTiers().length);
    });

    it('renders each tier row with its catalog thinkingMode (opus is always-on since 2026-09-28)', () => {
      const lines = specTable(catalog);
      for (const tier of catalog.listTiers()) {
        const row = lines.find((l) => l.startsWith(`| \`${tier}\``));
        expect(row).toMatch(new RegExp(`\\| ${catalog.getModel(tier).thinkingMode} \\|$`));
      }
      expect(lines.find((l) => l.startsWith('| `opus`'))).toMatch(/\| always-on \|$/);
    });

    it('includes every tier id from the catalog', () => {
      const body = specTable(catalog).join('\n');
      for (const tier of catalog.listTiers()) {
        expect(body).toContain(`\`${catalog.getModel(tier).id}\``);
      }
    });
  });

  describe('renderDoc', () => {
    const doc = renderDoc(catalog);

    it('carries the GENERATED do-not-hand-edit header', () => {
      expect(doc).toContain('GENERATED by scripts/gen-model-catalog-docs.js');
      expect(doc).toContain('lib/core/model-catalog.js');
    });

    it('documents the fable constraints from catalog data', () => {
      expect(doc).toContain('claude-fable-5');
      expect(doc).toContain('always-on');
      expect(doc).toContain('refusal');
      for (const key of catalog.getModel('fable').constraints) {
        expect(doc).toContain(key);
      }
    });

    it('derives the effective cost factor from the catalog (no hardcode drift)', () => {
      expect(doc).toContain(`~${catalog.getCostFactor('fable')}×`);
    });

    it('every "price × tokenizer" breakdown multiplies back to getCostFactor(fable)', () => {
      // The headline factor above was catalog-derived while its breakdown was
      // typed by hand ("price 2×"), so after the 2026-09-28 re-price the doc
      // read "~3.25× (price 2× × tokenizer 1.3×)" — a sum that does not add
      // up. Pin the breakdown to the same catalog numbers as the headline.
      const baseline = catalog.getModel(catalog.BASELINE_TIER);
      const fable = catalog.getModel('fable');
      const parts = [...doc.matchAll(/price ([\d.]+)× × tokenizer ([\d.]+)×/g)];
      expect(parts.length).toBe(2); // fable section + routing cost warning
      for (const [, price, tokenizer] of parts) {
        expect(Number(price)).toBe(fable.priceInPerMTok / baseline.priceInPerMTok);
        expect(Number(tokenizer)).toBe(fable.tokenizerCoeff);
        expect(Number(price) * Number(tokenizer))
          .toBeCloseTo(catalog.getCostFactor('fable'), 10);
      }
    });

    it('names the baseline from the catalog, never a retired model name', () => {
      const id = catalog.getModel(catalog.BASELINE_TIER).id;
      expect(doc).toContain(`the \`${catalog.BASELINE_TIER}\` baseline, \`${id}\``);
      expect(doc).not.toContain('Opus 4.8');
      // The label is set off by commas, not a parenthesis, so it never nests
      // inside the parentheses the prose already opens around it.
      expect(doc).not.toContain(`baseline (\`${id}\`)`);
    });

    it('states the routing policy: fable is opt-in, default stays opus', () => {
      expect(doc).toContain('opt-in');
      expect(doc).toContain('Default routing stays **Opus**');
      expect(doc).toContain('deep-async→fable');
    });

    it('contains no stale "fable cannot be a subagent" phrasing', () => {
      expect(doc).not.toMatch(/cannot be a subagent tier/i);
      expect(doc).not.toMatch(/API-only/i);
    });
  });
});
